# -*- coding: utf-8 -*-
"""2a.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pyEvLnKUZsLQEDPPiaFZrkWbxWBhGxR0
"""

import pandas as pd
from datetime import datetime, date, time
import sqlite3
from google.colab import drive

"""Jeftini senzori"""

drive.mount('/content/gdrive')
csv = pd.read_csv('/content/gdrive/My Drive/Colab Notebooks/data/jeftini_senzori.txt', sep=";", header=None, parse_dates=["measurement_date"], names =["measurement_datetime","measurement_date","measurement_time","d","temperature","humidity","g","h","lowcost_pm2.5","j","k","l","m","n","o"])
csv['measurement_datetime'] = csv['measurement_date'].astype(str) + " " + csv['measurement_time']

columns = ['measurement_datetime','temperature','humidity','lowcost_pm2.5']
js = pd.DataFrame(csv, columns=columns)
display(js)

"""Skupi senzori"""

ss = pd.read_excel(r'/content/gdrive/My Drive/Colab Notebooks/data/skupi_senzori.xlsx', header = [0], engine = 'openpyxl')
display(ss)

"""Filter skupih senzora"""

ss['date_beginning'] = (ss['date_beginning']).astype(str) + " " + ss['time_beginning']
ss['date_beginning'] = pd.to_datetime(ss['date_beginning'])
ss['date_end'] = (ss['date_end']).astype(str) + " " + ss['time_end']
ss['date_end'] = pd.to_datetime(ss['date_end'])
del ss["time_beginning"], ss["time_end"]
display(ss)

"""Merge"""

js['measurement_datetime'] = pd.to_datetime(js['measurement_datetime'], format='%Y/%m/%d %H:%M:%S')
ss['date_beginning']= pd.to_datetime(ss['date_beginning'], format='%Y/%m/%d %H:%M:%S') + pd.DateOffset(hours=-2)
ss['date_end']= pd.to_datetime(ss['date_end'], format='%Y/%m/%d %H:%M:%S') + pd.DateOffset(hours=-2)

conn = sqlite3.connect(':memory:')
js.to_sql('js', conn, index=False)
ss.to_sql('ss', conn, index=False)

qry = '''
    select * from js join ss on js.measurement_datetime between ss.date_beginning and ss.date_end
    '''

df = pd.read_sql_query(qry, conn)
df.to_excel('2a.xlsx')